### ISSUE TITLE
no log messages received

### ISSUE THREAD

**Issue by kemijoki** [Graylog2/graylog-plugin-cef#7]
I installed the CEF-plugin using the .deb-package, restarted graylog and defined a new input. However, no matter if I am using UDP or TCP, no logmessages are shown in graylog, although tcpdump is showing traffic, netstat shows, that the port is open. I entered 2 syslog-servers into the device I want to get the messages from, 1 points to the CEF-input, the other points to a raw-input. 
In the graylog-server.log I can just see complains about the raw-message, but no other message regarding the CEF-plugin. 
```
2016-09-08T21:34:31.211+02:00 ERROR [DecodingProcessor] Error processing message RawMessage{id=438f88a0-75fb-11e6-a200-0050569e73a3, journalOffset=128801836, codec=CEF, payloadSize=672, timestamp=2016-09-08T19:34:31.210Z, remoteAddress=/1.2.3.4:47863}
```
I have no idea how to look further.

Kind regards,
Mira

I am using graylog 2.1

**Comment by kemijoki** [comment]
Hi,
no I got some error messages:

2016-09-09T13:04:45.969+02:00 ERROR [DecodingProcessor] Unable to decode raw message 37bfb900-767d-11e6-a200-0050569e73a3 (journal offset 128832740) encoded as CEF received from /1.2.3.4:47863.
2016-09-09T13:04:45.969+02:00 ERROR [DecodingProcessor] Error processing message RawMessage{id=37bfb900-767d-11e6-a200-0050569e73a3, journalOffset=128832740, codec=CEF, payloadSize=672, timestamp=2016-09-09T11:04:45.968Z, remoteAddress=/1.2.3.4:47863}
org.graylog.plugins.cef.parser.CEFParser$ParserException: This message was not recognized as CEF and could not be parsed.
        at org.graylog.plugins.cef.parser.CEFParser.parse(CEFParser.java:71) ~[?:?]
        at org.graylog.plugins.cef.codec.CEFCodec.decode(CEFCodec.java:59) ~[?:?]
        at org.graylog2.shared.buffers.processors.DecodingProcessor.processMessage(DecodingProcessor.java:143) ~[graylog.jar:?]
        at org.graylog2.shared.buffers.processors.DecodingProcessor.onEvent(DecodingProcessor.java:86) [graylog.jar:?]
        at org.graylog2.shared.buffers.processors.ProcessBufferProcessor.onEvent(ProcessBufferProcessor.java:58) [graylog.jar:?]
        at org.graylog2.shared.buffers.processors.ProcessBufferProcessor.onEvent(ProcessBufferProcessor.java:35) [graylog.jar:?]
        at com.lmax.disruptor.WorkProcessor.run(WorkProcessor.java:143) [graylog.jar:?]
        at com.codahale.metrics.InstrumentedThreadFactory$InstrumentedRunnable.run(InstrumentedThreadFactory.java:66) [graylog.jar:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_102]


The message which could not be recognized as CEF was this:

<158>CEF:0|Trend Micro|Deep Discovery Inspector|3.83.1170|1537|Unsuccessful logon to Kerberos|4|dvc=1.2.3.4 dvcmac=aa:bb:cc:dd:ee:ff dvchost=host deviceExternalId=234234234-56456456-234243423 rt=Sep 09 2016 12:22:53 GMT+02:00 app=KERBEROS deviceDirection=1 dhost=host2 dst=10.20.30.40 dpt=23423 dmac=ff:ee:dd:cc:bb:aa shost=host3 src=10.20.30.50 spt=88 smac=ab:cd:ef:fe:dc:ba fileType=-65536 fsize=0 act=not blocked cn3Label=Threat Type cn3=2 destinationTranslatedAddress=10.20.30.40 sourceTranslatedAddress=10.20.30.50 suid=user cnt=4 cat=Authentication cs6Label=pAttackPhase cs6=Lateral Movement flexNumber1Label=vLANId flexNumber1=1111 


Hope this helps any further.

Kind regards,
Mira

**Comment by titleistfour** [comment]
I'm having the same issue with Graylog 2.1.1+01d50e5, OSSEC 2.8.3 and latest release of this plugin on CentOS 6 boxes.  Exact same errors.  Any help troubleshooting would be great. I've done the same verification as the poster and am using a CEF UDP input.  Tcpdump shows the traffic is reaching the server just fine, but the plugin fails to recognize the message as CEF.

2016-10-05T05:12:24.158-05:00 ERROR [DecodingProcessor] Unable to decode raw message 35d2e8d1-8ae4-11e6-b3b7-1262a9e4007f (journal offset 262713) encoded as CEF received from /172.31.1.137:45205.
2016-10-05T05:12:24.158-05:00 ERROR [DecodingProcessor] Error processing message RawMessage{id=35d2e8d1-8ae4-11e6-b3b7-1262a9e4007f, journalOffset=262713, codec=CEF, payloadSize=318, timestamp=2016-10-05T10:12:24.157Z, remoteAddress=/172.31.1.137:45205}
org.graylog.plugins.cef.parser.CEFParser$ParserException: This message was not recognized as CEF and could not be parsed.
        at org.graylog.plugins.cef.parser.CEFParser.parse(CEFParser.java:71) ~[?:?]
        at org.graylog.plugins.cef.codec.CEFCodec.decode(CEFCodec.java:59) ~[?:?]
        at org.graylog2.shared.buffers.processors.DecodingProcessor.processMessage(DecodingProcessor.java:143) ~[graylog.jar:?]
        at org.graylog2.shared.buffers.processors.DecodingProcessor.onEvent(DecodingProcessor.java:86) [graylog.jar:?]
        at org.graylog2.shared.buffers.processors.ProcessBufferProcessor.onEvent(ProcessBufferProcessor.java:58) [graylog.jar:?]
        at org.graylog2.shared.buffers.processors.ProcessBufferProcessor.onEvent(ProcessBufferProcessor.java:35) [graylog.jar:?]
        at com.lmax.disruptor.WorkProcessor.run(WorkProcessor.java:143) [graylog.jar:?]
        at com.codahale.metrics.InstrumentedThreadFactory$InstrumentedRunnable.run(InstrumentedThreadFactory.java:66) [graylog.jar:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]

Thanks,
Jay

**Comment by cmschube** [comment]
Same issue here, trying to send in CEF logs from OSSEC v2.9R3, and from auditd using the audisp-cef plugin. Both give the "This message was not recognized as CEF and could not be parsed." message.

**Comment by titleistfour** [comment]
@lennartkoopmann  The 1.1.1 release fixed this issue for me.  My guess is it was the additional whitespace cause it to not recognize the message as valid DEF.  Sweet!!  Thanks

Jay

**Comment by kemijoki** [comment]
Hi,
unfortunatly version 1.1.1 was not helpful for me, I am still getting this error:

org.graylog.plugins.cef.parser.CEFParser$ParserException: This message was not r                                                     ecognized as CEF and could not be parsed.
        at org.graylog.plugins.cef.parser.CEFParser.parse(CEFParser.java:71) ~[?                                                     :?]
        at org.graylog.plugins.cef.codec.CEFCodec.decode(CEFCodec.java:59) ~[?:?                                                     ]

Kind regards,
Mira

**Comment by marcobelmonte** [comment]
I want to know what the fuck is wrong with these vendors like - for example in my case - Trend Micro that offers the ability to send logs in CEF format but don't follow the fucking standards. I don't want to encapsulate my logs in syslog - I want them to be transported in CEF format but instead these bungholes over at Trend give me CEF via Syslog... Anyways, I'm in the same boat as everyone else. Now, I just read in this plugin's readme file that I can fix it with a preprocessor rule. Obviously that's the road I'll need to travel but on a Thurday night when I'm already working late and need to get home this doesn't sound like a quick task. So thank you Trend Micro. Fuck you very much.

**Comment by marcRBD** [comment]
the same problem here.

- graylog-server                       2.2.3-1
- cef plugin 1.1.1 ou 1.2.0
- ossec v2.9.0

**Comment by marcRBD** [comment]
hello
the logs
"java.lang.IllegalArgumentException: Invalid format: "Apr 19 09:40:04"
        at org.joda.time.format.DateTimeFormatter.parseDateTime(DateTimeFormatter.java:945) ~[graylog.jar:?]
"
i try pipelines or this but can't get it right
http://docs.graylog.org/en/2.1/pages/extractors.html#the-standard-date-converter

someone has a solution ?

**Comment by andr3scrivener** [comment]
Same problem . Any solution for this problem?

**Comment by marcobelmonte** [comment]
I am in the same boat. It would be helpful to maybe show us how we could use the pipeline feature since I gave it a try and obviously am not using the parse_cef function correctly. I think we are all in the same boat here.

**Comment by lennartkoopmann** [comment]
Please post an example message and the rule you are trying to run on it and I can help.

**Comment by marcRBD** [comment]
hello
the cef message:

Apr 26 10:00:41 CEF:0|Trend Micro Inc.|OSSEC HIDS|v2.9.0|30315|Invalid URI (bad client request).|5|dvc=ossec2-9 
cs2=ossec2-9->/var/log/apache2/error.log cs2Label=Location classification= apache,invalid_request, 
src=10.66.150.103 spt=46160 shost=10.66.150.103 cs3Label=SrcCity cs3=RFC1918 IP msg=[Wed Apr 26 10:00:39.401335 2017] 
[core:error] [pid 29766:tid 139794206095104] [client 10.66.112.103:46160] AH00126: Invalid URI in request GET . HTTP/1.0

and i use the graylog-plugin-cef, nothing more !

thanks

**Comment by lennartkoopmann** [comment]
@marcRBD You have to extract the CEF string out of the message (the message is not CEF format compliant) in a pipeline and then run the `parse_cef` function over the extracted String to add all the fields to your message with `set_fields()`.

The CEF string is this:

```
CEF:0|Trend Micro Inc.|OSSEC HIDS|v2.9.0|30315|Invalid URI (bad client request).|5|dvc=ossec2-9
cs2=ossec2-9->/var/log/apache2/error.log cs2Label=Location classification= apache,invalid_request,
src=10.66.150.103 spt=46160 shost=10.66.150.103 cs3Label=SrcCity cs3=RFC1918 IP msg=[Wed Apr 26 10:00:39.401335 2017]
[core:error] [pid 29766:tid 139794206095104] [client 10.66.112.103:46160] AH00126: Invalid URI in request GET . HTTP/1.0
```

**Comment by hackdefendr** [comment]
I'm see this issue too. According to the latest ArcSight CEF guide the proper header format for CEF is:

`Jan 18 11:07:53 host CEF:Version|Device Vendor|Device Product|Device
Version|Device Event Class ID|Name|Severity|[Extension]`

Here is a copy of a log from one of my honeypots: 
`2017-08-31T20:31:26.325068 CEF:0|ThreatStream|MHN|1.0|dionaea.connections|Connection to Honeypot|10|deviceDirection=0 cs2=network cs2Label=ids_type cs3=dionaea cs3Label=app src=xxx.xxx.xxx.xxx cs1=Dionaea cs1Label=vendor_product dpt=1433 spt=4579 dst=xxx.xxx.xxx.xxx proto=tcp`

If your plugin is only looking at the log starting at CEF:0 then that is incorrect. It should be looking for the timestamp and host as well.

**Comment by githubuserx** [comment]
I have a Fortinet FortiGate firewall and couldn't get it to work either. The firewall sends the CEF messages in the format mentioned by @hackdefendr. The currently used regex definitely does not work with Syslog envelopes/CEF headers containing a hostname or IP address.
https://github.com/graylog-labs/graylog-plugin-cef/blob/0bcb91c628ae07c54c3ff7d98f54e6e536259a0a/src/main/java/org/graylog/plugins/cef/parser/SyslogCEFParser.java#L22

I made the following changes to the current regex for better compliance to [RFC 3164](https://tools.ietf.org/html/rfc3164#section-4).
```regex
^(?:<\\d+>)?([a-zA-Z]{3}\\s+\\d{1,2} \\d{1,2}:\\d{1,2}:\\d{1,2}) (?:\\p{Graph}+)? ?(CEF:.+)$
```
Shouldn't be much different performance-wise, but can propably be improved. Works with all currently supported formats and the one specified in the ArcSight CEF Guide.

**Comment by joschi** [comment]
Please give the latest version of the plugin a try (depending on your Graylog version):

* [2.2.0-beta.1](https://github.com/Graylog2/graylog-plugin-cef/releases/tag/2.2.0-beta.1) (for Graylog 2.2.x)
* [2.3.0-beta.1](https://github.com/Graylog2/graylog-plugin-cef/releases/tag/2.3.0-beta.1) (for Graylog 2.3.x)

You might have to re-create your CEF input depending on your message sources, e. g. a "CEF TCP/UDP input" for ArcSight instead of a "CEF Syslog TCP/UDP input".

While not all issues are fixed, these new releases might work better for you than the old ones.

**Comment by hackdefendr** [comment]
My graylog is v2.3.1 and will not start with graylog-plugin-cef-2.3.0-beta.1.jar in the plugins folder.

**Comment by joschi** [comment]
@hackdefendr This has been fixed in version [2.3.0-beta.2](https://github.com/Graylog2/graylog-plugin-cef/releases/tag/2.3.0-beta.2).

**Comment by hackdefendr** [comment]
Confirmed beta2 fixes the startup issue.

**Comment by githubuserx** [comment]
The message parsing does still not work for me in the new versions. I'm pretty sure it's because the Syslog parser always looks for the priority part (`<\\d+>`) of the message as in the RFC.
The log messages though have the following format (captured with `nc`):
```
Sep 21 17:07:40 hostname CEF:0|Fortinet|Fortigate|v5.6.2|00015|traffic:forward start|3|FTNTFGTlogid=0 cat=traffic:forward FTNTFGTsubtype=forward FTNTFGTlevel=notice FTNTFGTvd=root FTNTFGTlogtime=0 src=0.0.0.0 spt=0 deviceInboundInterface=x FTNTFGTsrcintfrole=x dst=0.0.0.0 dpt=0 deviceOutboundInterface=x FTNTFGTdstintfrole=undefined FTNTFGTpoluuid=x externalId=0 proto=0 act=start FTNTFGTpolicyid=0 FTNTFGTpolicytype=policy app=HTTPS FTNTFGTdstcountry=United States FTNTFGTsrccountry=Reserved FTNTFGTtrandisp=snat sourceTranslatedAddress=0.0.0.0 sourceTranslatedPort=0 FTNTFGTduration=0 out=0 in=0 FTNTFGTsentpkt=0 FTNTFGTappcat=unscanned
```
I think they implemented it according to the example in the ArcSight guide and therefore it's not strictly following the RFC for the Syslog header.

**Comment by joschi** [comment]
@githubuserx That's not syslog. Syslog messages *always* start with the priority field (`<\\d+>`), see https://tools.ietf.org/html/rfc3164 and https://tools.ietf.org/html/rfc5424.

> `Sep 21 17:07:40 hostname CEF:0|Fortinet|Fortigate|v5.6.2|00015|traffic:forward start|3|FTNTFGTlogid=0 [...]`

If that line is exactly what's going over the wire, you have to use a *Raw* (Plaintext) CEF input.

**Comment by githubuserx** [comment]
I just tried again all different types of CEF inputs without success and seems obvious to me that it can't work with the current regex in both parsers, since the raw CEF input can only start with whitespace characters (`^\\s*`).
I know that it's not Syslog, but it seems to be the same header execpt the priority part. I could use pipelines to extract only the (`CEF:[...]`) part but then I'd lose the header information. Since the CEF guide explicitly mentions the format as the "Syslog" header for CEF messages I thought it would be nice to support this format directly in the parser.

Excerpt from the [ArcSight Guide](https://community.saas.hpe.com/t5/ArcSight-Connectors/ArcSight-Common-Event-Format-CEF-Guide/ta-p/1589306?attachment-id=65284) PDF, page 5:

![cef-guide](https://user-images.githubusercontent.com/5589968/30744529-c45ec19a-9fa2-11e7-8837-e5a3bb3711eb.PNG)

So I think they intended to omit the priority prefix of the Syslog header and still called it Syslog. Fortinet and probably others then implemented it strictly following this guide.

**Comment by marcRBD** [comment]
hello
i give a try in ossec 2.9.2/Graylog 2.2.x , still not working for me, the message in a pcap trace
"2>Sep 22 14:58:34 CEF:0|Trend Micro Inc.|OSSEC HIDS|v2.9.2|117003|Web server 404 error code.|3|dvc=upgrade-ossec29 cs1=(stretch) 10.11.25.29->/var/log/apache2/access.log cs1Label=Location classification= web,accesslog, src=192.168.0.5 shost=192.168.0.5 cs4Label=SrcCity 
cs4=RFC1918 IP msg=192.168.0.5 - - [22/Sep/2017:14:57:30 +0200] 
"GET /7Lt2kgar.var HTTP/1.1" 404 504 "-" "Mozilla/5.00 (Nikto/2.1.5) (Evasions:None) (Test:map_codes)"
"
I will try some advice you gave.
Best regards

**Comment by joschi** [comment]
Next plugin iteration:

* https://github.com/Graylog2/graylog-plugin-cef/releases/tag/2.2.0-beta.2
* https://github.com/Graylog2/graylog-plugin-cef/releases/tag/2.3.0-beta.3

**Comment by joschi** [comment]
And even more (only fixes AMQP and Kafka CEF inputs):

* https://github.com/Graylog2/graylog-plugin-cef/releases/tag/2.2.0-beta.3
* https://github.com/Graylog2/graylog-plugin-cef/releases/tag/2.3.0-beta.4

**Comment by githubuserx** [comment]
Just tested the latest version and it seems to work perfectly so far 👍 - thank you for the effort!

**Comment by jalogisch** [comment]
as this looks solved, i'll close this.

If you do not feel, please reopen the issue.
